use infodb;


CREATE TABLE IF NOT EXISTS TEAM_INFO (
    TEAM_CODE INT AUTO_INCREMENT PRIMARY KEY,
    TEAM_NAME VARCHAR(100) NOT NULL,
    TEAM_DETAIL VARCHAR(500),
    USE_YN CHAR(2) NOT NULL DEFAULT 'Y', 
    CHECK(USE_YN IN ('Y', 'N')) 
);

CREATE TABLE IF NOT EXISTS MEMBER_INFO(
	MEMBER_CODE INT AUTO_INCREMENT PRIMARY KEY,
    MEMVBER_NAME VARCHAR(70) NOT NULL,
    BIRTH_dATE DATE,
    DIVISION_CODE CHAR(2),
    DETAIL_INFO VARCHAR(500),
    CONTACT VARCHAR(50) NOT NULL,
    TEAM_CODE INT, # FK
    ACTIVE_STATUS CHAR(2) NOT NULL DEFAULT 'Y',
    CHECK(ACTIVE_STATUS IN ('Y', 'N', 'H')),
    CONSTRAINT FK_TEAM_CODE FOREIGN KEY (TEAM_CODE) REFERENCES TEAM_INFO (TEAM_CODE)
);